[package]
name = "vjoyrs"
version = "0.1.0"
authors = ["Lyneca <atraguliauniliantauthr@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.5"
